alias dfg='$(which git) -c include.path=${HOME}/.config/git/dfg.config --git-dir ${HOME}/.local/share/dotfiles/repo --work-tree=${HOME}'
alias git='git -c include.path=${HOME}/.config/git/git.config'
alias vim='vim -u ${XDG_CONFIG_HOME:-$HOME/.config}/vim/vimrc'
alias brl='vim -u ${XDG_CONFIG_HOME:-$HOME/.config}/beryl/vimrc'
alias vimdiff='vimdiff -u ${XDG_CONFIG_HOME:-$HOME/.config}/vim/vimrc'
alias lazy='NVIM_APPNAME=nvim-lazy nvim'
alias mvim='NVIM_APPNAME=nvim-mini nvim'
