#!/bin/bash

# headers, arguments and anything that needs to stand out
# export LESS_TERMCAP_md=$'\033[1;38;2;255;102;0m'                  # bold, orange fg
# export LESS_TERMCAP_me=$'\033[0m'                                 # reset
#
# # argument values, links, directories
# export LESS_TERMCAP_us=$'\033[4;1;38;2;255;255;255m'              # underline, bold, white fg
# export LESS_TERMCAP_ue=$'\033[0m'                                 # reset
#
# # bottom line with search help and found patterns
# export LESS_TERMCAP_so=$'\033[0;38;2;0;0;0;48;2;49;50;240m' # bold, yellow fg, blue bg
# export LESS_TERMCAP_se=$'\033[0m'                                 # reset
#
export GROFF_NO_SGR=1         # For Konsole and Gnome-terminal
#
# export LESS="--RAW-CONTROL-CHARS"

alias man='man --pager "most -s"'
