return {
  "nvim-treesitter/nvim-treesitter",
  dependencies = {
    "mason-org/mason.nvim"
  },
  branch = "main",
  version = false,
  build = Toolkit.treesitter.build,
  opts = {
    auto_install = true,
    ensure_installed = {
      "bash",
      "c",
      "diff",
      "html",
      "javascript",
      "jsdoc",
      "json",
      "jsonc",
      "lua",
      "luadoc",
      "luap",
      "markdown",
      "markdown_inline",
      "printf",
      "python",
      "query",
      "regex",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
    },
  },
}
