#!/bin/bash

# source me!

git init --bare $HOME/.dotfiles/repo
alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/repo/ --work-tree=$HOME'
dotfiles config --local status.showUntrackedFiles no
echo 'alias dotfiles="/usr/bin/git --git-dir=$HOME/.dotfiles/repo --work-tree=$HOME"' >> $HOME/.bashrc
echo 'alias dotfiles-tree="dotfiles ls-files | tree --fromfile ."' >> $HOME/.bashrc
