alias dfg='git -c status.showUntrackedFiles=no -c user.name="sokhouw" -c user.email="marcin.sokolowski@gmail.com" --git-dir ${HOME}/.local/share/dotfiles/repo --work-tree=${HOME}'
alias vim='vim -u ${XDG_CONFIG_HOME:-$HOME/.config}/vim/vimrc'
alias vimdiff='vimdiff -u ${XDG_CONFIG_HOME:-$HOME/.config}/vim/vimrc'
alias lazy='NVIM_APPNAME=nvim-lazy nvim'
alias mvim='NVIM_APPNAME=nvim-mini nvim'
