require("toolkit")

require("config/clipboard")
require("config/diagnostic")
require("config/filetypes")
require("config/options")
require("config/lsp")
require("config/lazy")
require("config/diffcolors")
require("config/keymaps")
